// Code generated by MockGen. DO NOT EDIT.
// Source: adapters/helm/adapter.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/machado-br/helm-api/adapters/models"
)

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter {
	mock := &MockAdapter{ctrl: ctrl}
	mock.recorder = &MockAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	return m.recorder
}

// InstallChart mocks base method.
func (m *MockAdapter) InstallChart(releaseName string, dryRun bool, chart models.Chart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallChart", releaseName, dryRun, chart)
	ret0, _ := ret[0].(error)
	return ret0
}

// InstallChart indicates an expected call of InstallChart.
func (mr *MockAdapterMockRecorder) InstallChart(releaseName, dryRun, chart interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallChart", reflect.TypeOf((*MockAdapter)(nil).InstallChart), releaseName, dryRun, chart)
}

// ListReleases mocks base method.
func (m *MockAdapter) ListReleases() ([]models.Release, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReleases")
	ret0, _ := ret[0].([]models.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReleases indicates an expected call of ListReleases.
func (mr *MockAdapterMockRecorder) ListReleases() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReleases", reflect.TypeOf((*MockAdapter)(nil).ListReleases))
}

// UninstallRelease mocks base method.
func (m *MockAdapter) UninstallRelease(releaseName string, dryRun bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UninstallRelease", releaseName, dryRun)
	ret0, _ := ret[0].(error)
	return ret0
}

// UninstallRelease indicates an expected call of UninstallRelease.
func (mr *MockAdapterMockRecorder) UninstallRelease(releaseName, dryRun interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UninstallRelease", reflect.TypeOf((*MockAdapter)(nil).UninstallRelease), releaseName, dryRun)
}
