apiVersion: apps/v1
kind: Deployment

metadata:
  name: helm-api
  labels:
    app: helm-api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-api
  template:
    metadata:
      labels:
        app: helm-api
    spec:
      containers:
        - name: helm-api
          image: 774429751797.dkr.ecr.us-west-2.amazonaws.com/helm-api:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: CLUSTER_NAME
              value: "my-cluster"
            - name: NAMESPACE
              value: "default"
            - name: AWS_REGION
              value: "us-west-2"
            - name: DEPLOYED
              value: "true"
            - name: GIN_MODE
              value: "release"
      serviceAccountName: helm-api
      automountServiceAccountToken: true
