apiVersion: v1
kind: Pod
metadata:
  name: helm-api
spec:
  containers:
    - name: helm-api
      image: 774429751797.dkr.ecr.us-west-2.amazonaws.com/helm-api:latest
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        - name: CLUSTER_NAME
          value: "my-cluster"
        - name: NAMESPACE
          value: "default"
        - name: AWS_REGION
          value: "us-west-2"
  serviceAccountName: helm-api
  volumes:
    - name: vault-token
      projected:
        sources:
          - serviceAccountToken:
              path: vault-token
              expirationSeconds: 7200
              audience: vault
