apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: helm-api
  name: helm-api
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: helm-api
subjects:
  - kind: ServiceAccount
    name: helm-api
    namespace: default
