apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: helm-api
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::774429751797:role/my-role
  name: helm-api
automountServiceAccountToken: false
