apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: helm-api
  name: helm-api
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
